### ISSUE TITLE
Issue with CapyMenu(QAM) Header and footer custom color

### ISSUE THREAD

**Issue by AllEternalsDeck** [Kalyvara/CSS-Loader-releases#2]
In CapyMeny (QAM), when selecting a custom color in "[In-game] Header and Footer Background Color", only the first color selector works. The second and third color selectors change the color of the first selector, instead of changing their own colors (it's a bit weird to explain, but a quick tinker with the three color selectors should show the problem more intuitively than me explaining it through words)

**Comment by Kalyvara** [comment]
Thanks for reporting. This has been fixed on my end.

On a side note it seems that the latest Steam client update broke some UI styling, so CapyMenu's next update should be available once I get the whole thing fixed up and the theme gets approval from the staff
