### ISSUE TITLE
CapyMenu [SteamMenu] "HOME" text and icon remain white except when selected.

### ISSUE THREAD

**Issue by loudurdee** [Kalyvara/CSS-Loader-releases#8]
Steam Menu opens with HOME selected by default, with highlighted text color, selected icon color, and selected item background color gradient applied. the rest of the menu is also themed correctly with the custom colors for icon and text. 

ISSUE: on selecting anything other than home, all other menu items behave as expected except HOME. Everything else changes between highlighted/selected and unselected colors while scrolling menu, but HOME text and icon remains white until highlighted again.

**Comment by Kalyvara** [comment]
Thanks for the report, please grab the revised `common.css` file here https://github.com/Kalyvara/SDeck-CapyMenu-Steam-Menu/blob/main/LEGACY/common.css
and replace the old one in `/home/deck/homebrew/themes/CapyMenu (Steam Menu)` with this version

**Comment by loudurdee** [comment]
That resolved it for me. HOME is themed as expected. I think my deck is perfect now, your menus are like the chef's kiss of it. Thanks so much for all your efforts! Closing Issue! 😀
